name: ace-592-sae
channels:
  - conda-forge
  - defaults
dependencies:
  - urllib3
  - regex
  - plotly
  - scipy
  - xarray
  - beautifulsoup4
  - jupyter_core
  - matplotlib-base
  - jsonschema
  - emoji
  - python=3
  - seaborn
  - wordcloud
  - matplotlib
  - econtools
  - rasterio
  - nltk
  - unidecode
  - jupyter_client
  - scikit-learn
  - requests
  - bs4
  - pandas
  - rasterstats
  - dask-core
  - lxml
  - dask
  - pillow
  - pip
  - multiprocess
  - notebook
  - geopandas
  - gensim
  - tweepy
  - rise
  - spotipy
  - scikit-image
  - overpy
  - graphviz
  - python-graphviz
  - scrapy
  - selenium